// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeatherWardrobeApi.Data;

#nullable disable

namespace WeatherWardrobeApi.Migrations
{
    [DbContext(typeof(WeatherWardrobeContext))]
    [Migration("20241119135738_ExtendTemperatureRange")]
    partial class ExtendTemperatureRange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClothingItemWeatherCondition", b =>
                {
                    b.Property<int>("ClothingItemsClothingItemId")
                        .HasColumnType("integer");

                    b.Property<int>("WeatherConditionsWeatherConditionId")
                        .HasColumnType("integer");

                    b.HasKey("ClothingItemsClothingItemId", "WeatherConditionsWeatherConditionId");

                    b.HasIndex("WeatherConditionsWeatherConditionId");

                    b.ToTable("ClothingItemWeatherCondition", (string)null);

                    b.HasData(
                        new
                        {
                            ClothingItemsClothingItemId = 13,
                            WeatherConditionsWeatherConditionId = 1
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 13,
                            WeatherConditionsWeatherConditionId = 2
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 11,
                            WeatherConditionsWeatherConditionId = 1
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 11,
                            WeatherConditionsWeatherConditionId = 2
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 11,
                            WeatherConditionsWeatherConditionId = 3
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 12,
                            WeatherConditionsWeatherConditionId = 1
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 12,
                            WeatherConditionsWeatherConditionId = 2
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 12,
                            WeatherConditionsWeatherConditionId = 3
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 12,
                            WeatherConditionsWeatherConditionId = 4
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 14,
                            WeatherConditionsWeatherConditionId = 1
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 14,
                            WeatherConditionsWeatherConditionId = 2
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 14,
                            WeatherConditionsWeatherConditionId = 3
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 15,
                            WeatherConditionsWeatherConditionId = 1
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 15,
                            WeatherConditionsWeatherConditionId = 2
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 15,
                            WeatherConditionsWeatherConditionId = 3
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 15,
                            WeatherConditionsWeatherConditionId = 4
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 1,
                            WeatherConditionsWeatherConditionId = 3
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 1,
                            WeatherConditionsWeatherConditionId = 4
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 1,
                            WeatherConditionsWeatherConditionId = 5
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 2,
                            WeatherConditionsWeatherConditionId = 6
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 2,
                            WeatherConditionsWeatherConditionId = 7
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 3,
                            WeatherConditionsWeatherConditionId = 7
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 3,
                            WeatherConditionsWeatherConditionId = 8
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 3,
                            WeatherConditionsWeatherConditionId = 9
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 3,
                            WeatherConditionsWeatherConditionId = 10
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 4,
                            WeatherConditionsWeatherConditionId = 5
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 4,
                            WeatherConditionsWeatherConditionId = 6
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 5,
                            WeatherConditionsWeatherConditionId = 8
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 5,
                            WeatherConditionsWeatherConditionId = 9
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 5,
                            WeatherConditionsWeatherConditionId = 10
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 6,
                            WeatherConditionsWeatherConditionId = 4
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 6,
                            WeatherConditionsWeatherConditionId = 5
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 6,
                            WeatherConditionsWeatherConditionId = 6
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 6,
                            WeatherConditionsWeatherConditionId = 7
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 7,
                            WeatherConditionsWeatherConditionId = 1
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 7,
                            WeatherConditionsWeatherConditionId = 2
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 7,
                            WeatherConditionsWeatherConditionId = 3
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 7,
                            WeatherConditionsWeatherConditionId = 4
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 8,
                            WeatherConditionsWeatherConditionId = 8
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 8,
                            WeatherConditionsWeatherConditionId = 9
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 8,
                            WeatherConditionsWeatherConditionId = 10
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 9,
                            WeatherConditionsWeatherConditionId = 1
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 9,
                            WeatherConditionsWeatherConditionId = 2
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 9,
                            WeatherConditionsWeatherConditionId = 3
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 9,
                            WeatherConditionsWeatherConditionId = 4
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 10,
                            WeatherConditionsWeatherConditionId = 9
                        },
                        new
                        {
                            ClothingItemsClothingItemId = 10,
                            WeatherConditionsWeatherConditionId = 10
                        });
                });

            modelBuilder.Entity("WeatherWardrobeApi.Models.ClothingItem", b =>
                {
                    b.Property<int>("ClothingItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClothingItemId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ClothingItemId");

                    b.ToTable("ClothingItems");

                    b.HasData(
                        new
                        {
                            ClothingItemId = 1,
                            Description = "Heavy insulated winter coat",
                            ImageURL = "coat.jpg",
                            Name = "Winter Coat"
                        },
                        new
                        {
                            ClothingItemId = 2,
                            Description = "Light windbreaker jacket",
                            ImageURL = "jacket.jpg",
                            Name = "Light Jacket"
                        },
                        new
                        {
                            ClothingItemId = 3,
                            Description = "Cotton t-shirt",
                            ImageURL = "tshirt.jpg",
                            Name = "T-Shirt"
                        },
                        new
                        {
                            ClothingItemId = 4,
                            Description = "Warm wool sweater",
                            ImageURL = "sweater.jpg",
                            Name = "Sweater"
                        },
                        new
                        {
                            ClothingItemId = 5,
                            Description = "Casual shorts",
                            ImageURL = "shorts.jpg",
                            Name = "Shorts"
                        },
                        new
                        {
                            ClothingItemId = 6,
                            Description = "Regular fit jeans",
                            ImageURL = "pants.jpg",
                            Name = "Long Pants"
                        },
                        new
                        {
                            ClothingItemId = 7,
                            Description = "Warm beanie",
                            ImageURL = "hat.jpg",
                            Name = "Winter Hat"
                        },
                        new
                        {
                            ClothingItemId = 8,
                            Description = "Summer sandals",
                            ImageURL = "sandals.jpg",
                            Name = "Sandals"
                        },
                        new
                        {
                            ClothingItemId = 9,
                            Description = "Insulated winter boots",
                            ImageURL = "boots.jpg",
                            Name = "Winter Boots"
                        },
                        new
                        {
                            ClothingItemId = 10,
                            Description = "Light sleeveless top",
                            ImageURL = "tank.jpg",
                            Name = "Tank Top"
                        },
                        new
                        {
                            ClothingItemId = 11,
                            Description = "Base layer thermal underwear",
                            ImageURL = "thermal.jpg",
                            Name = "Thermal Underwear"
                        },
                        new
                        {
                            ClothingItemId = 12,
                            Description = "Insulated snow pants",
                            ImageURL = "snowpants.jpg",
                            Name = "Snow Pants"
                        },
                        new
                        {
                            ClothingItemId = 13,
                            Description = "Extreme cold weather parka",
                            ImageURL = "parka.jpg",
                            Name = "Arctic Parka"
                        },
                        new
                        {
                            ClothingItemId = 14,
                            Description = "Thermal neck protection",
                            ImageURL = "gaiter.jpg",
                            Name = "Neck Gaiter"
                        },
                        new
                        {
                            ClothingItemId = 15,
                            Description = "Heavy-duty winter gloves",
                            ImageURL = "gloves.jpg",
                            Name = "Insulated Gloves"
                        });
                });

            modelBuilder.Entity("WeatherWardrobeApi.Models.WeatherCondition", b =>
                {
                    b.Property<int>("WeatherConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WeatherConditionId"));

                    b.Property<string>("ConditionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<string>("TemperatureRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WeatherConditionId");

                    b.ToTable("WeatherConditions");

                    b.HasData(
                        new
                        {
                            WeatherConditionId = 1,
                            ConditionName = "Arctic",
                            Temperature = 0.0,
                            TemperatureRange = "-40--30"
                        },
                        new
                        {
                            WeatherConditionId = 2,
                            ConditionName = "Extreme Cold",
                            Temperature = 0.0,
                            TemperatureRange = "-30--20"
                        },
                        new
                        {
                            WeatherConditionId = 3,
                            ConditionName = "Very Cold",
                            Temperature = 0.0,
                            TemperatureRange = "-20--10"
                        },
                        new
                        {
                            WeatherConditionId = 4,
                            ConditionName = "Cold",
                            Temperature = 0.0,
                            TemperatureRange = "-10-0"
                        },
                        new
                        {
                            WeatherConditionId = 5,
                            ConditionName = "Chilly",
                            Temperature = 0.0,
                            TemperatureRange = "0-10"
                        },
                        new
                        {
                            WeatherConditionId = 6,
                            ConditionName = "Cool",
                            Temperature = 0.0,
                            TemperatureRange = "10-15"
                        },
                        new
                        {
                            WeatherConditionId = 7,
                            ConditionName = "Mild",
                            Temperature = 0.0,
                            TemperatureRange = "15-20"
                        },
                        new
                        {
                            WeatherConditionId = 8,
                            ConditionName = "Warm",
                            Temperature = 0.0,
                            TemperatureRange = "20-25"
                        },
                        new
                        {
                            WeatherConditionId = 9,
                            ConditionName = "Hot",
                            Temperature = 0.0,
                            TemperatureRange = "25-30"
                        },
                        new
                        {
                            WeatherConditionId = 10,
                            ConditionName = "Very Hot",
                            Temperature = 0.0,
                            TemperatureRange = "30-40"
                        });
                });

            modelBuilder.Entity("ClothingItemWeatherCondition", b =>
                {
                    b.HasOne("WeatherWardrobeApi.Models.ClothingItem", null)
                        .WithMany()
                        .HasForeignKey("ClothingItemsClothingItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeatherWardrobeApi.Models.WeatherCondition", null)
                        .WithMany()
                        .HasForeignKey("WeatherConditionsWeatherConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
